version: '3'

services:
  postgres:
    image: postgres:11.1-alpine
    ports:
      - 5430:5432
    environment:
      POSTGRES_DB: okko
      POSTGRES_USER: okko
      POSTGRES_PASSWORD: root
    volumes:
      - "db:/var/lib/postgresql/data/"

  redis:
    image: redis:6-alpine
    hostname: redis
    ports:
      - 6379:6379

volumes:
  db:
