# Generated by Django 3.2.8 on 2022-04-25 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220409_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.taskstatus'),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='link',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
